name: web_cabinet_nkfo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.1.1+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
    

  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  url_strategy: ^0.2.0
  data_table_2: ^2.3.5
  syncfusion_flutter_datepicker: ^20.2.40

  dio: ^4.0.6
  compute: ^1.0.2
  json_annotation: ^4.6.0
  retrofit: ^3.0.1+1

  dio_http_formatter: ^2.1.0

  injector: ^2.0.0

  equatable: ^2.0.3
  flutter_bloc: ^7.1.0

  flutter_svg: ^1.0.3

  dartx: ^1.1.0

  # responsive_ui: ^3.0.0
  responsive_ui: ^2.1.0

  simple_circular_progress_bar: ^1.0.2

  responsive_builder: ^0.4.2

  google_fonts: ^5.1.0

  # flutter_masked_text2: ^0.9.1
  mask_text_input_formatter: ^2.3.0

  configurable_expansion_tile_null_safety: ^2.0.3
    # git:
    #   url: https://github.com/LuckyWins/configurable_expansion_tile.git
    #   ref: master

  qr_flutter: ^4.0.0

  shared_preferences: ^2.0.15

  email_validator: ^2.1.16

  excel: #^2.0.0-null-safety-3
    git:
      url: https://github.com/james-d-hasselman/excel
      ref: bug-167

 # excel: #^2.0.0-null-safety-3
  #   git:
  #     url: https://github.com/justkawal/excel.git
  #     ref: b3adcfa49dfd2bfb55dae77c877a326618d5eea1    

  dropdown_search: ^5.0.6
  # dropdown_search2: ^1.0.2
  data_table_plus: ^0.0.1
  pattern_formatter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.3
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/files/
    - assets/icon/
    - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages