name: payment_tracking_module
description: Модуль розыска платежей для Беларусбанка.


version: 2.0.0+9

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  

  # Routing
  auto_route: ^7.7.1
  auto_route_generator: ^7.2.0
  get_it: ^7.6.0
  url_strategy: ^0.2.0


  # http
  dio_http_formatter: ^3.1.0
  url_launcher: ^6.1.12
  dio: ^5.3.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  jwt_decoder: ^2.0.1
  dart_jsonwebtoken: ^2.8.2
  web_socket_channel: ^2.4.0


  # bl
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  bloc_concurrency: ^0.2.2
  dartx: ^1.2.0
  intl: ^0.18.0
  either_dart: ^1.0.0
  provider: ^6.0.5
  


  # data
  shared_preferences: ^2.2.0
  uuid: ^3.0.7
  yaml: ^3.1.1
  excel: ^2.1.0

  # ui
  cupertino_icons: ^1.0.2
  responsive_ui: ^3.0.1
  responsive_builder: ^0.7.0
  simple_circular_progress_bar: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  data_table_2: ^2.5.6
  dropdown_search: ^5.0.6
  flutter_svg: ^2.0.7


  # textInput 
  google_fonts: ^5.1.0
  mask_text_input_formatter: ^2.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/



