name: fl_qr_module
description: "A new Flutter module project."
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dio_http_formatter: ^3.1.0

  flutter_svg: ^2.0.7

  bloc_concurrency: ^0.2.5

  mobile_scanner: ^4.0.1

  equatable: ^2.0.3

  flutter_bloc: ^8.1.5

  crypto: ^3.0.1

  encrypt: ^5.0.1

  injector: ^3.0.0

  slang: ^3.21.0

  slang_flutter: ^3.21.0

  qr_flutter: ^4.0.0

  sms_autofill: ^2.2.0

  permission_handler: ^11.3.0

  dartx: ^1.2.0

  dio: ^5.3.0

  json_annotation: ^4.8.1

  retrofit: ^4.0.1

  modal_bottom_sheet: ^3.0.0

  shared_preferences: ^2.0.12

  flutter_secure_storage: ^9.0.0

  local_auth: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^8.1.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1



flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  module:
    androidX: true
    androidPackage: com.example.fl_qr_module
    iosBundleIdentifier: com.example.flQrModule
