name: bpc
description: Кабинет юридического лица

version: 2.0.3+28

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  dio: ^5.3.2
  retrofit: ^4.0.1
  json_annotation: ^4.6.0
  dio_http_formatter: ^3.1.0

  injector: ^3.0.0

  rxdart: ^0.27.5

  crypto: ^3.0.2

  intl: ^0.18.0

  dartx: ^1.1.0

  qr_flutter: ^4.0.0

  flutter_slidable: ^3.0.0

  custom_check_box: ^0.0.4

  shared_preferences: ^2.0.15

  pull_to_refresh: ^2.0.0

  url_launcher: ^6.1.5

  web_socket_channel: ^2.2.0

  flutter_svg: ^2.0.7

  local_auth: ^2.1.0

  flutter_secure_storage: ^9.0.0

  flutter_screen_lock: ^9.0.1

  cupertino_icons: ^1.0.5

  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0

  modal_bottom_sheet: ^2.1.2

  # qr_code_scanner: ^1.0.0
  mobile_scanner: ^3.4.1
  
  permission_handler: ^11.0.0

  mask_text_input_formatter: ^2.3.0

  email_validator: ^2.1.16

  # responsive_scaffold: ^1.3.0+2

  keyboard_actions: ^4.0.1

  responsive_builder: ^0.7.0

  package_info_plus: ^4.1.0

  device_preview: ^1.1.0

  syncfusion_flutter_datepicker: ^23.1.38

  expandable_text: ^2.3.0
  auto_route: ^7.8.3
   
    
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^7.0.8
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  auto_route_generator: ^7.3.1



flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/logo1024.png"
  image_path_ios: "assets/icon/logo1024ios.png"

flutter_native_splash:
  image: assets/images/splash500.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/