name: helppay_core
description: HelpPay core
version: 2.0.0
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

  dio: ^5.3.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1

  dartx: ^1.0.0

  intl: ^0.18.0

  # fast_i18n: ^5.12.6
  slang: ^3.21.0
  slang_flutter: ^3.21.0

  modal_bottom_sheet: ^2.0.1

  shared_preferences: ^2.0.12

  flutter_secure_storage: ^8.0.0

  local_auth: ^2.0.2

  tuple: ^2.0.0

  decimal: ^2.2.0

  encrypt: ^5.0.1
  
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.8
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: