name: helppay_web_app
description: Платежное приложение web версия


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

# EDIT!!!
dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

  auto_route: ^7.7.1

  auto_route_generator: ^7.2.0
  
  get_it: ^7.2.0

  flutter_localizations:
    sdk: flutter

  helppay_core:
    path: ../core

  dio_http_formatter: ^3.1.0

  url_strategy: ^0.2.0

  responsive_builder: ^0.7.0
  
  flutter_svg: ^2.0.7

  bloc_concurrency: ^0.2.0

  # qr_code_scanner: ^0.7.0
    # git:
    #   url: https://github.com/LuckyWins/qr_code_scanner.git
    #   ref: master
  # mobile_scanner: ^3.3.0

  rxdart: ^0.27.3

  crypto: ^3.0.1

  injector: ^3.0.0

  responsive_ui: ^3.0.1

  email_validator: ^2.0.1

  data_table_2: ^2.3.5

  mask_text_input_formatter: ^2.3.0

  cupertino_icons: ^1.0.4

  flutter_screen_lock: ^9.0.1
  # flutter_screen_lock:
  #   git:
  #     url: https://github.com/LuckyWins/flutter_screen_lock.git
  #     ref: master

  string_mask: ^1.0.0

  # fast_i18n: ^5.12.6
  slang: ^3.21.0
  slang_flutter: ^3.21.0

  pull_to_refresh: ^2.0.0

  roundcheckbox: ^2.0.4+1

  device_preview: ^1.0.0

  syncfusion_flutter_datepicker: ^22.1.39

  expandable_text: ^2.3.0

  url_launcher: ^6.1.5

  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

  retrofit_generator: ^7.0.8
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/logo1024.png"
  image_path_ios: "assets/icon/logo1024ios.png"

flutter_native_splash:
  image: assets/images/splash500.png
  color: "#FFFFFF"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/guides/
